### ISSUE TITLE
Failed to import "nonebot_plugin_guild_patch"

### ISSUE THREAD

**Issue by Misaka13514** [mnixry/nonebot-plugin-guild-patch#16]
version: 0.2.3

logs:
```
nonebot   | Checking for script in /app/prestart.sh
nonebot   | Running script /app/prestart.sh
nonebot   | Running inside /app/prestart.sh, you could add migrations to this file, e.g.:
nonebot   | 
nonebot   | #! /usr/bin/env bash
nonebot   | 
nonebot   | # Let the DB start
nonebot   | sleep 10;
nonebot   | # Run migrations
nonebot   | alembic upgrade head
nonebot   | 
nonebot   | [2023-05-24 11:26:20 +0000] [1] [INFO] Starting gunicorn 20.1.0
nonebot   | [2023-05-24 11:26:20 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
nonebot   | [2023-05-24 11:26:20 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
nonebot   | [2023-05-24 11:26:20 +0000] [6] [INFO] Booting worker with pid: 6
nonebot   | {"loglevel": "INFO", "workers": 1, "bind": "0.0.0.0:8080", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": 1, "host": "0.0.0.0", "port": "8080"}
nonebot   | 05-24 11:26:20 [SUCCESS] nonebot | NoneBot is initializing...
nonebot   | 05-24 11:26:20 [INFO] nonebot | Current Env: prod
nonebot   | 05-24 11:26:21 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
nonebot   | 05-24 11:26:22 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
nonebot   | 05-24 11:26:23 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_bing_chat"
nonebot   | 05-24 11:26:23 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
nonebot   | 05-24 11:26:24 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_datastore"
nonebot   | 05-24 11:26:24 [SUCCESS] nonebot_plugin_access_control | Loaded plugin for: OneBot V11
nonebot   | 05-24 11:26:24 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_access_control"
nonebot   | 05-24 11:26:24 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mcstatus" from "atribot.plugins.nonebot_plugin_mcstatus"
nonebot   | 05-24 11:26:24 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_tietie" from "atribot.plugins.nonebot_plugin_tietie"
nonebot   | 05-24 11:26:24 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_minecraft_server_check" from "atribot.plugins.nonebot_plugin_minecraft_server_check"
nonebot   | 05-24 11:26:24 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_pic" from "atribot.plugins.nonebot_plugin_pic"
nonebot   | 05-24 11:26:25 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_repeat" from "atribot.plugins.nonebot_plugin_repeat"
nonebot   | 05-24 11:26:27 [ERROR] nonebot | Failed to import "nonebot_plugin_guild_patch"
nonebot   | Traceback (most recent call last):
nonebot   |   File "/usr/local/bin/gunicorn", line 8, in <module>
nonebot   |     sys.exit(run())
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
nonebot   |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 231, in run
nonebot   |     super().run()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
nonebot   |     Arbiter(self).run()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 202, in run
nonebot   |     self.manage_workers()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
nonebot   |     self.spawn_workers()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
nonebot   |     self.spawn_worker()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
nonebot   |     worker.init_process()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
nonebot   |     super(UvicornWorker, self).init_process()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
nonebot   |     self.load_wsgi()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
nonebot   |     self.wsgi = self.app.wsgi()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
nonebot   |     self.callable = self.load()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
nonebot   |     return self.load_wsgiapp()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
nonebot   |     return util.import_app(self.app_uri)
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
nonebot   |     mod = importlib.import_module(module)
nonebot   |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
nonebot   |     return _bootstrap._gcd_import(name[level:], package, level)
nonebot   |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
nonebot   |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
nonebot   |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
nonebot   |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
nonebot   |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
nonebot   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
nonebot   |   File "/app/bot.py", line 27, in <module>
nonebot   |     nonebot.load_from_toml("pyproject.toml")
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
nonebot   |     return load_all_plugins(plugins, plugin_dirs)
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
nonebot   |     return manager.load_all_plugins()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
nonebot   |     return set(
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
nonebot   |     filter(None, (self.load_plugin(name) for name in self.available_plugins))
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
nonebot   |     module = importlib.import_module(name)
nonebot   |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
nonebot   |     return _bootstrap._gcd_import(name[level:], package, level)
nonebot   |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
nonebot   |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
nonebot   |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
nonebot   |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
nonebot   |     super().exec_module(module)
nonebot   |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
nonebot   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
nonebot   |   File "/usr/local/lib/python3.11/site-packages/ELF_RSS2/__init__.py", line 8, in <module>
nonebot   |     from . import command
nonebot   |   File "<frozen importlib._bootstrap>", line 1234, in _handle_fromlist
nonebot   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
nonebot   |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
nonebot   |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
nonebot   |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
nonebot   |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
nonebot   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
nonebot   |   File "/usr/local/lib/python3.11/site-packages/ELF_RSS2/command/__init__.py", line 1, in <module>
nonebot   |     from . import (
nonebot   |   File "<frozen importlib._bootstrap>", line 1234, in _handle_fromlist
nonebot   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
nonebot   |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
nonebot   |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
nonebot   |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
nonebot   |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
nonebot   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
nonebot   |   File "/usr/local/lib/python3.11/site-packages/ELF_RSS2/command/add_dy.py", line 16, in <module>
nonebot   |     require("nonebot_plugin_guild_patch")  # noqa
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/load.py", line 168, in require
nonebot   |     plugin = load_plugin(name)
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
nonebot   |     return manager.load_plugin(module_path)
nonebot   | > File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 154, in load_plugin
nonebot   |     raise RuntimeError(
nonebot   | RuntimeError: Module nonebot_plugin_guild_patch is not loaded as a plugin! Make sure not to import it before loading.
nonebot   | 05-24 11:26:27 [ERROR] nonebot | Failed to import "ELF_RSS2"
nonebot   | Traceback (most recent call last):
nonebot   |   File "/usr/local/bin/gunicorn", line 8, in <module>
nonebot   |     sys.exit(run())
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
nonebot   |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 231, in run
nonebot   |     super().run()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
nonebot   |     Arbiter(self).run()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 202, in run
nonebot   |     self.manage_workers()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
nonebot   |     self.spawn_workers()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
nonebot   |     self.spawn_worker()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
nonebot   |     worker.init_process()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
nonebot   |     super(UvicornWorker, self).init_process()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
nonebot   |     self.load_wsgi()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
nonebot   |     self.wsgi = self.app.wsgi()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
nonebot   |     self.callable = self.load()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
nonebot   |     return self.load_wsgiapp()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
nonebot   |     return util.import_app(self.app_uri)
nonebot   |   File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
nonebot   |     mod = importlib.import_module(module)
nonebot   |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
nonebot   |     return _bootstrap._gcd_import(name[level:], package, level)
nonebot   |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
nonebot   |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
nonebot   |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
nonebot   |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
nonebot   |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
nonebot   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
nonebot   |   File "/app/bot.py", line 27, in <module>
nonebot   |     nonebot.load_from_toml("pyproject.toml")
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
nonebot   |     return load_all_plugins(plugins, plugin_dirs)
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
nonebot   |     return manager.load_all_plugins()
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
nonebot   |     return set(
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
nonebot   |     filter(None, (self.load_plugin(name) for name in self.available_plugins))
nonebot   | > File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
nonebot   |     module = importlib.import_module(name)
nonebot   |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
nonebot   |     return _bootstrap._gcd_import(name[level:], package, level)
nonebot   |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
nonebot   |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
nonebot   |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
nonebot   |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
nonebot   |     super().exec_module(module)
nonebot   |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
nonebot   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
nonebot   |   File "/usr/local/lib/python3.11/site-packages/ELF_RSS2/__init__.py", line 8, in <module>
nonebot   |     from . import command
nonebot   |   File "/usr/local/lib/python3.11/site-packages/ELF_RSS2/command/__init__.py", line 1, in <module>
nonebot   |     from . import (
nonebot   |   File "/usr/local/lib/python3.11/site-packages/ELF_RSS2/command/add_dy.py", line 16, in <module>
nonebot   |     require("nonebot_plugin_guild_patch")  # noqa
nonebot   |   File "/usr/local/lib/python3.11/site-packages/nonebot/plugin/load.py", line 170, in require
nonebot   |     raise RuntimeError(f'Cannot load plugin "{name}"!')
nonebot   | RuntimeError: Cannot load plugin "nonebot_plugin_guild_patch"!
nonebot   | [2023-05-24 11:26:27 +0000] [6] [INFO] Started server process [6]
nonebot   | [2023-05-24 11:26:27 +0000] [6] [INFO] Waiting for application startup.
nonebot   | 05-24 11:26:27 [INFO] nonebot_plugin_apscheduler | Scheduler Started
nonebot   | 05-24 11:26:27 [INFO] nonebot_plugin_datastore | 数据库初始化完成
nonebot   | [2023-05-24 11:26:27 +0000] [6] [INFO] Application startup complete.
nonebot   | [2023-05-24 11:26:33 +0000] [6] [INFO] ('192.168.16.3', 47218) - "WebSocket /onebot/v11/ws/" [accepted]
nonebot   | 05-24 11:26:33 [INFO] nonebot | OneBot V11 | Bot 1945872835 connected
nonebot   | [2023-05-24 11:26:33 +0000] [6] [INFO] connection open
```

**Comment by mnixry** [comment]
> `RuntimeError: Module nonebot_plugin_guild_patch is not loaded as a plugin! Make sure not to import it before loading.`

应该是没作为插件加载直接 import 了

**Comment by Misaka13514** [comment]
问题已解决，谢谢 @mnixry
