### ISSUE TITLE
升级到2.0.0后报错

### ISSUE THREAD

**Issue by moian98** [mnixry/nonebot-plugin-guild-patch#5]
所有代码都没动。。。
gocq：v1.0.0-rc1
nonebot2：2.0.0b2

报错：
`pydantic.errors.ConfigError: duplicate validator function "nonebot_plugin_guild_patch.models.GuildMessageEvent._validate_raw_message"; if this is intended, set `allow_reuse=True``

大佬知道是什么原因吗？

**Comment by mnixry** [comment]
试试升级`nonebot2`和`nonebot-adapter-onebot`到最新版本

**Comment by moian98** [comment]
> 尝试升级`nonebot2`和`nonebot-adapter-onebot`到最新版本

试过了，还是一样的报错。。。

**Comment by mnixry** [comment]
@Ailitonia 你有头绪吗👀

**Comment by moian98** [comment]
```
06-22 19:57:11 [ERROR] nonebot | Failed to import "nonebot_plugin_guild_patch"
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/YYY/qingya_new\bot.py", line 27, in <module>
    nonebot.load_plugin("nonebot_plugin_guild_patch")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_guild_patch\__init__.py", line 6, in <module>
    from .models import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_guild_patch\models.py", line 30, in <module>
    class GuildMessageEvent(MessageEvent):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_guild_patch\models.py", line 43, in GuildMessageEvent
    def _validate_raw_message(cls, raw_message):
  File "pydantic\class_validators.py", line 88, in pydantic.class_validators.validator.dec
    f_cls = _prepare_validator(f, allow_reuse)
  File "pydantic\class_validators.py", line 147, in pydantic.class_validators._prepare_validator
    raise ConfigError(f'duplicate validator function "{ref}"; if this is intended, set `allow_reuse=True`')
pydantic.errors.ConfigError: duplicate validator function "nonebot_plugin_guild_patch.models.GuildMessageEvent._validate_raw_message"; if this is intended, set `allow_reuse=True`
```

**Comment by Ailitonia** [comment]
@moian98 能提供一下 python 版本和 pydantic 的版本吗？
我是 py 3.10.4, pydantic 1.9.1, 复现不了这个异常

**Comment by moian98** [comment]
> @moian98能提供一下python版本和pydantic的版本吗？ 我是py 3.10.4, pydantic 1.9.1, 复现不了这个异常
python版本是3.8.10，pydantic 是1.9.0

**Comment by moian98** [comment]
> python版本是3.8.10，pydantic 是1.9.0

python版本是3.8.10，pydantic 是1.9.0

**Comment by moian98** [comment]
> @moian98能提供一下python版本和pydantic的版本吗？ 我是py 3.10.4, pydantic 1.9.1, 复现不了这个异常
@Ailitonia 
python版本是3.8.10，pydantic 是1.9.0

**Comment by Ailitonia** [comment]
>  python版本是3.8.10，pydantic 是1.9.0

在这个环境试了还是没法复现啊😂

另外刚刚测试的时候发现这行的类型标注在 3.8 就不能用啊, 你是不是自己改了啥（

https://github.com/mnixry/nonebot-plugin-guild-patch/blob/78e55cba3865d19bbfe285aa12dfa923aa991361/nonebot_plugin_guild_patch/models.py#L88

**Comment by mnixry** [comment]
> 另外刚刚测试的时候发现这行的类型标注在 3.8 就不能用啊, 你是不是自己改了啥（
> 
> https://github.com/mnixry/nonebot-plugin-guild-patch/blob/78e55cba3865d19bbfe285aa12dfa923aa991361/nonebot_plugin_guild_patch/models.py#L88

@Ailitonia 这个是3.9的语法，这个插件要求在3.7.3以上都能运行

你要不提个PR再修一下👀

**Comment by Ailitonia** [comment]
> @Ailitonia 这个是3.9的语法，这个插件要求在3.7.3以上都能运行
> 
> 你要不提个PR再修一下👀

这几天摸了，已经有pr了 e73b017233d46905abb8464ad03086a6a3ed14bf

另外这个报错有头绪吗，我换了好几个版本组合都复现不出来

**Comment by Quan666** [comment]
能把修改后的发布到 pypi 么 https://github.com/mnixry/nonebot-plugin-guild-patch/pull/6
@mnixry

**Comment by mnixry** [comment]
> 能把修改后的发布到 PyPI 么

对不起对不起对不起我忘记了QAQ
