### ISSUE TITLE
在使用`on_command`时匹配频道消息报错

### ISSUE THREAD

**Issue by lgc2333** [mnixry/nonebot-plugin-guild-patch#8]
## 插件代码

nonebot 版本 2.0.0b5

```py
from nonebot import on_command
from nonebot.permission import SUPERUSER
from nonebot.matcher import Matcher

h_ping = on_command("ping", aliases={"Ping", "PING"}, rule=SUPERUSER)


@h_ping.handle()
async def _(matcher: Matcher):
    await matcher.finish("Pong~")
```

## 报错

```py
11-08 21:02:47 [WARNING] nonebot | Error while parsing command for event
Traceback (most recent call last):
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 193, in handle_event
    await handle_event(self, event)
> File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\message.py", line 293, in handle_event
    TrieRule.get_value(bot, event, state)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\rule.py", line 82, in get_value
    message = event.get_message()
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 48, in get_message
    raise ValueError("Event has no message!")
ValueError: Event has no message!
```

```py
11-08 21:03:43 [ERROR] nonebot | Rule check failed for <Matcher from src.plugins.ping, type=message, priority=1, temp=False>.
Traceback (most recent call last):
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\message.py", line 132, in _check_matcher
    ) or not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\internal\matcher.py", line 299, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\internal\rule.py", line 70, in __call__
    results = await asyncio.gather(
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 89, in __call__
    values = await self.solve(**kwargs)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 201, in solve
    values[field.name] = check_field_type(field, value)
  File "D:\Programs\1\venv\virtualenvs\nb2-oneclick-DZq-2Leo-py3.10\lib\site-packages\nonebot\dependencies\utils.py", line 51, in check_field_type
    _, errs_ = field.validate(value, {}, loc=())
  File "pydantic\fields.py", line 832, in pydantic.fields.ModelField.validate
    assert cls is not None
AssertionError
```

**Comment by mnixry** [comment]
你确定这个插件正确加载了吗

**Comment by lgc2333** [comment]
> 你确定这个插件正确加载了吗

没加载怎么可能运行插件matcher然后报错

**Comment by mnixry** [comment]
> 没加载怎么可能运行插件matcher然后报错

额 我的意思是 `nonebot-plugin-guild-patch` 这个插件加载了吗 看看日志

因为你提供的代码和报错堆栈里面我好像没有看到任何和本仓库有关的信息

**Comment by lgc2333** [comment]
> > 没加载怎么可能运行插件matcher然后报错
> 
> 额 我的意思是 `nonebot-plugin-guild-patch` 这个插件加载了吗 看看日志
> 
> 因为你提供的代码和报错堆栈里面我好像没有看到任何和本仓库有关的信息

好像没有 我加载之后再看看

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/200597656-3e561d01-a9b9-447a-aa21-2d76209277ad.png)
呃啊啊啊啊啊啊

**Comment by lgc2333** [comment]
```py
11-08 23:07:50 [SUCCESS] nonebot | ONEBOT V11 3076823485 | [message.guild.channel]: Message BACoiV20P3lBAAAAAACMf9YAAAAAAAAIFw== from 144115218860429136@[Guild:47438831636412737/Channel:9207766] "须弥丛林（带主宅）25973317394"
11-08 23:07:50 [ERROR] nonebot | Rule check failed for <Matcher from src.plugins.ping, type=message, priority=1, temp=False>.
Traceback (most recent call last):
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\lgc2333\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\nonebot\message.py", line 132, in _check_matcher
    ) or not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\nonebot\internal\matcher.py", line 299, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\nonebot\internal\rule.py", line 70, in __call__
    results = await asyncio.gather(
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 89, in __call__
    values = await self.solve(**kwargs)
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 201, in solve
    values[field.name] = check_field_type(field, value)
  File "D:\Programs\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-7q2IGbEy-py3.10\lib\site-packages\nonebot\dependencies\utils.py", line 51, in check_field_type
    _, errs_ = field.validate(value, {}, loc=())
  File "pydantic\fields.py", line 832, in pydantic.fields.ModelField.validate
    assert cls is not None
AssertionError
```
貌似频道普通消息也会报错 但是是 `AssertionError`  是数据结构问题吗
我的gocq版本 `v1.0.0-rc3`

**Comment by lgc2333** [comment]
还是说要在插件里require才行

**Comment by lgc2333** [comment]
> 还是说要在插件里require才行

require过了也不行
![image](https://user-images.githubusercontent.com/59048777/200599501-cdea7556-9fb1-4f4c-a225-b132d5d450eb.png)

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/200602869-707ecebc-039c-458a-880e-675ce39f9642.png)
奇怪 为什么group message也会 迷惑

**Comment by lgc2333** [comment]
不是你插件的问题 我会慢慢排查

**Comment by lgc2333** [comment]
真的不好意思 **我是大傻逼**
我把 permission 填到 rule 里去了
实在麻烦了呜呜
